### ISSUE TITLE
Improve connector inventory

### ISSUE THREAD

**Issue by h33p** [memflow/memflow#17]
Print connector paths, versions, etc in the logs.

Avoid duplicate connectors (have some path map to avoid it)

**Comment by ko1N** [comment]
Additionally, we should add a check for the rustc version to make sure the abi matches.

**Comment by CasualX** [comment]
Something I briefly discussed with ko1N:

Rust does not have a stable ABI, not even 'stable when using the same compiler', consider:

A resource allocated in one binary and freed in another is pretty much UB because both binaries can specify their own allocators. For obvious reasons it is important to deallocate memory _in the same binary_ as was used to allocate.

Example: https://github.com/memflow/memflow/blob/master/memflow-derive/src/lib.rs#L37

This looks like it allocates a box with the intention of passing the resulting box through FFI into another binary which may free it.

Of course if you're using the system allocator this will probably 'work in practice'. I'm not sure if this is something you want to rely on.

Technically the only safe way to pass Rust data types is through its C FFI stuff (with all the restrictions it implies).

**Comment by ko1N** [comment]
The current implementation works in practice but you are correct. To prevent any rust ABI issues and allocator issues a proper FFI should be exposed through the derive macro that implements all trait functions of PhysicalMemory.

Instead of implementing deref on the ConnectorInstance it should also just implement and forward declare the trait.

This would then solve the need to check for the rustc version. Only the Inventory version will be relevant (and we check it already).

**Comment by ko1N** [comment]
The exposed functions could look something along this:

```rust
    pub conn_create: extern "C" fn(args: *const c_char) -> *mut PhysicalMemoryBox,

    pub conn_phys_read_raw_list: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,
    pub conn_phys_write_raw_list: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,
    pub conn_metadata: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,

    pub conn_drop: extern "C" fn(phys_mem: *mut PhysicalMemoryBox),
```

**Comment by h33p** [comment]
> The exposed functions could look something along this:
> 
> ```rust
>     pub conn_create: extern "C" fn(args: *const c_char) -> *mut PhysicalMemoryBox,
> 
>     pub conn_phys_read_raw_list: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,
>     pub conn_phys_write_raw_list: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,
>     pub conn_metadata: extern "C" fn(phys_mem: *mut PhysicalMemoryBox) -> i32,
> 
>     pub conn_drop: extern "C" fn(phys_mem: *mut PhysicalMemoryBox),
> ```
We should pass references of PhysicalMemoryBox, rather then pointers.

conn_create should return Option<&mut PhysicalMemoryBox>.

They are more ergonomic, and ABI compatible

**Comment by ko1N** [comment]
The first iteration of the new connector interface is now on the 'next' branch.
I think it might be possible (and good) if we removed that CloneablePhysicalMemory / PhysicalMemoryBox 'hack' from our earlier implementation.

The CloneablePhysicalMemory is currently just used in the FFI.

**Comment by ko1N** [comment]
The new oslayers are merged to next.
